disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - nesting
  - orphaned_doc_comment
  - no_space_in_method_call
  - type_body_length
  - opening_brace
  - switch_case_alignment
  - file_length
function_parameter_count: 10
line_length: 155
cyclomatic_complexity: 20
identifier_name:
  excluded: # excluded via string array
    - id
